export default {
  products: [
    {
      _id: "1",
      name: "Running shoes",
      category: "shoes",
      brand: "nike",
      image: "./images/product-1.jpg",
      price: 58,
      rating: 4.6,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "2",
      name: "Running shoes",
      category: "shoes",
      brand: "under armour",
      image: "./images/product-1.jpg",
      price: 58,
      rating: 4.6,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "3",
      name: "Running shoes",
      category: "shoes",
      brand: "nike",
      image: "./images/product-1.jpg",
      price: 58,
      rating: 4.6,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "4",
      name: "Running shoes",
      category: "shoes",
      brand: "adidas",
      image: "./images/product-1.jpg",
      price: 58,
      rating: 4.6,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "5",
      name: "Running shoes",
      category: "shoes",
      brand: "asics",
      image: "./images/product-1.jpg",
      price: 58,
      rating: 4.6,
      numReviews: 10,
      countInStock: 5,
    },
  ],
};
